edition = "2021"
tab_spaces = 4
max_width = 100
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Default"
reorder_imports = true
imports_granularity = "Crate"
format_code_in_doc_comments = true
wrap_comments = true
format_strings = true
normalize_comments = true
reorder_modules = true
